name: Daily Forex Prediction

on:
  schedule:
    # Jalan setiap jam 00:00 UTC (Jam 07:00 WIB)
    - cron: '0 0 * * *'
  workflow_dispatch: # Agar bisa ditrigger manual lewat tombol klik

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install tabulate # Untuk tampilan tabel cantik di log

      - name: Run Prediction Script
        run: python forex_bot.py